spring:
  cloud:
    stream:
      function:
        definition: orderSupplier,paymentEventConsumer
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event
      kafka:
        binder:
          brokers: localhost:9092